### ISSUE TITLE
Feat: `Useful.empty_dir_contents/1` delete all files and directories in a dir but not the dir itself

### ISSUE THREAD

**Issue by nelsonic** [dwyl/useful#14]
While testing our `gitea` module we have a `/tmp` directory that fills up with sub directories and files.
We want to delete the contents of the `/tmp` directory recursively, but not the directory itself. 

My reading of https://hexdocs.pm/elixir/1.13/File.html is that this function does not already exist.
there is [`File.rm_rf/1`](https://hexdocs.pm/elixir/1.13/File.html#rm_rf/1) but that will delete the directory itself.
We don't want that. 

Going to do a bit more research. But thinking of just making this function with tests and shipping it so I can _use_ it. 💭

**Comment by nelsonic** [comment]
Code in PR #15 assigned for review. 
Package published to https://hex.pm/packages/useful/1.0.8
(cause I want to use over in `gitea` tests ASAP ... but very happy to update in response to any PR review/feedback)

**Comment by SimonLab** [comment]
> Package published to https://hex.pm/packages/useful/1.0.8
(cause I want to use over in gitea tests ASAP ... but very happy to update in response to any PR review/feedback)

What I'm doing when I want to test the package without publishing it is to use the `git` and `branch` options in mix.exs, for example:

```elixir
defp deps do
  [...,
    {:useful, git: "https://github.com/dwyl/useful.git", branch: "feat/empty_dir_contents-issue-#14"}
 ]
end
```

Otherwise I think we can update the `empty_dir_contents`
- use guard to check the type of the arguments is binary otherwise return error:
```elixir
def empty_dir_contents(dir) when is_binary(dir) do
...
end
 
def empty_dir_contents(_),
    do: {:error, "dir supplied to Useful.empty_dir_contents/1 is not a string"}
```

- Would deleting the folder itself and recreating an empty one with the same name work? This would allow us to use two function instead of listing all the files and folders and deleting them one by one?

**Comment by nelsonic** [comment]
@SimonLab very helpful. 🙌 
Definitely worth updating when we have some post-project rush time. ⏳ 
We should 100% add that to the code re-use part of our learn-elixir tutorial. 💡 
See: https://github.com/dwyl/learn-elixir/pull/146 🙏

**Comment by nelsonic** [comment]
@SimonLab Perhaps create a new issue "Refactor Nelson's [_Basic_](https://www.urbandictionary.com/define.php?term=ya%20basic) code". 😜

**Comment by nelsonic** [comment]
Closing as this is working for us: https://hexdocs.pm/useful/Useful.html#empty_dir_contents/1
Happy for anyone to refactor in the future. 👌
